"""updating tables

Revision ID: 14283e60ec4f
Revises: bab9e5b88460
Create Date: 2023-05-24 10:26:48.186951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14283e60ec4f'
down_revision = 'bab9e5b88460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bakeries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
